import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster position="top-right" toastOptions={{ 
          style: { background: '#fff', color: '#006634', border: '1px solid #e2e8f0', borderRadius: '12px', fontWeight: 500 },
          iconTheme: { primary: '#006634', secondary: '#fff' },
          success: { iconTheme: { primary: '#006634', secondary: '#fff' } }
        }} />
      </body>
    </html>
  );
}
